# Generated by Django 3.2.16 on 2025-10-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('recipe', 'user')},
        ),
    ]
