# Generated by Django 3.2.16 on 2025-10-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('recipe', 'user')},
        ),
    ]
